<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>IdentityWorkshop.Application</AssemblyName>
    <RootNamespace>IdentityWorkshop.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IdentityWorkshop.Domain\IdentityWorkshop.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>

